#!/bin/bash

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg VERSION=`cat VERSION` --build-arg NGINX_VER=`curl -s -L http://nginx.org/download/ | sed -n 's/.*href\=\"nginx-\(.*\)\.tar.gz\".*/\1/p' | sort -V | grep "$NGINX_MAINLINE_VER." | tail -n1` -t alinuxninja/nginxgw:latest -t alinuxninja/nginxgw:mainline .
